config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'orders#index'

  resources :orders
  resources :packages
  resources :users
  resources :qr_codes, only: %i[index]
  post '/scan', to: 'qr_codes#scan'
end

app/models/user.rb
# frozen_string_literal: true

# class for User Model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :trackable,
         :recoverable, :rememberable, :validatable

  enum role: %i[admin superadmin]

  validates :role, presence: true
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# class for Orders Controller
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: I18n.t('users.created')
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to users_path, notice: I18n.t('users.updated')
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      redirect_to users_path, notice: I18n.t('users.deleted')
    else
      redirect_to users_path, notice: I18n.t('users.is_not_deleted')
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :role, :password, :password_confirmation)
  end
end

app/views/users/edit.html.slim
= simple_form_for @user do |f|
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  = f.input :role, collection: [['Админ', 'admin'],['Супер админ', 'superadmin']]

  = f.button :submit, I18n.t('users.update'), class: 'btn btn-primary submit-button'

app/views/users/index.html.slim
.orders-container
  .creation-bnt
    = link_to I18n.t('users.create'), new_user_path, class: 'btn btn-info'

  table.table
    thead
      tr
        th = I18n.t('users.email')
        th = I18n.t('users.role')
        th = I18n.t('users.created_at')
    tbody
    - @users.each do |user|
      tr
        th
          = user.email
        th
          = user.role
        th
          = user.created_at.strftime("%F %T")
        th
          = link_to I18n.t('buttons.show'), user_path(user), class: 'btn btn-info'
        th
          = link_to I18n.t('buttons.edit'), edit_user_path(user), class: 'btn btn-primary'
        th
          = link_to I18n.t('buttons.delete'), user_path(user), method: :delete, class: 'btn btn-danger'

app/views/users/new.html.slim
.form_container
  = simple_form_for @user do |f|
    = f.input :email
    = f.input :password
    = f.input :password_confirmation
    = f.input :role, collection: [['Админ', 'admin'],['Супер админ', 'superadmin']]

    = f.button :submit, I18n.t('users.create'), class: 'btn btn-primary submit-button'

app/views/users/show.html.slim
.form_container
  div.form-group
    .field-label.control-label
      = I18n.t('users.email')
    .field.form-control
      = @user.email
  div.form-group
    .field-label.control-label
      = I18n.t('users.role')
    .field.form-control
      = @user.role
  div.form-group
    .field-label
      = I18n.t('users.password')
    .field.form-control
      = I18n.t('users.password_encrypted')
  div.form-group
    .field-label
      = I18n.t('users.created_at')
    .field.form-control
      = @user.created_at.strftime("%F %T")