config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'orders#index'

  resources :orders
  resources :packages
  resources :users
  resources :qr_codes, only: %i[index]
  post '/scan', to: 'qr_codes#scan'
end

app/models/order.rb
# frozen_string_literal: true

# class for Order Model
class Order < ApplicationRecord
  has_many :packages, inverse_of: :order
  belongs_to :user

  enum status: %i[active archive]

  validates :title, :customer_info, :order_info, :user_id, :status, presence: true

  accepts_nested_attributes_for :packages, reject_if: :all_blank, allow_destroy: true

  ransacker :id do
    Arel::Nodes::SqlLiteral.new(
      "regexp_replace(to_char(\"#{table_name}\".\"id\", '99999999'), ' ', '', 'g')"
    )
  end

  ransacker :status, formatter: proc { |v| statuses[v] } do |parent|
    parent.table[:status]
  end

  ransacker :created_at, type: :date do
    Arel.sql('date(created_at)')
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

# class for Orders Controller
class OrdersController < ApplicationController
  def index
    @q = Order.all.ransack(params[:q])
    @orders = @q.result.order('created_at DESC').paginate(page: params[:page], per_page: 10)
  end

  def new
    @order = Order.new
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to orders_path, notice: I18n.t('orders.created')
    else
      render 'new'
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])

    if @order.update_attributes(order_params)
      redirect_to orders_path, notice: I18n.t('orders.updated')
    else
      render 'edit'
    end
  end

  def destroy
    @order = Order.find(params[:id])

    if @order.destroy
      redirect_to orders_path, notice: I18n.t('orders.deleted')
    else
      redirect_to orders_path, notice: I18n.t('orders.is_not_deleted')
    end
  end

  private

  def order_params
    params.require(:order).permit(:title, :customer_info, :order_info, :user_id, :status,
                                  packages_attributes: %i[id size info order_id _destroy])
  end
end

app/helpers/order_helper.rb
module OrderHelper
  def order_statuses_ru
    {
      active: 'Активный',
      archive: 'Архивный'
    }
  end

  def order_statuses
    [
      ['Активный', 'active'],
      ['Архивный', 'archive']
    ]
  end
end

app/views/orders/_package_fields.html.slim
= f.input :size
= f.input :info

= link_to_remove_association 'Delete package', f, class: 'btn btn-warning btn-sm'

app/views/orders/_search_form.html.slim
  .seach-container
    = search_form_for @q, url: orders_path, builder: SimpleForm::FormBuilder do |f|
      .orders-search
        label = I18n.t('orders.id')
        = f.search_field :id_cont

        label = I18n.t('orders.title')
        = f.search_field :title_cont

        label = I18n.t('orders.customer_info')
        = f.search_field :customer_info_cont

      .orders-search
        label = I18n.t('orders.status')
        = f.select :status_eq, order_statuses.unshift(['',''])

        label = I18n.t('orders.created_at_gteq')
        = f.search_field :created_at_gteq, id: 'order_created_at_gt'
        span.input-group-addon
          i.fa.fa-calendar

        label = I18n.t('orders.created_at_lteq')
        = f.search_field :created_at_lteq, id: 'order_created_at_lt'
        span.input-group-addon
          i.fa.fa-calendar

        = f.submit I18n.t('buttons.search')

app/views/orders/edit.html.slim
= simple_form_for @order do |f|
  = f.input :title
  = f.input :customer_info
  = f.input :order_info
  = f.input :status, collection: order_statuses
  = f.button :submit, I18n.t('orders.update'), class: 'btn btn-primary submit-button'

app/views/orders/index.html.slim
.orders-container

  .creation-bnt
    = link_to I18n.t('orders.create'), new_order_path, class: 'btn btn-info'

  = render partial: 'orders/search_form'

  table.table
    thead
      tr
        th = I18n.t('orders.id')
        th = I18n.t('orders.title')
        th = I18n.t('orders.customer_info')
        th = I18n.t('orders.status')
        th = I18n.t('orders.created_at')
    tbody
    - @orders.each do |order|
      tr
        th
          = order.id
        th
          = order.title
        th
          = order.customer_info
        th
          = order_statuses_ru[order.status.try(:to_sym)]
        th
          = order.created_at.strftime("%F %T")
        th
          = link_to I18n.t('buttons.show'), order_path(order), class: 'btn btn-info'
        th
          = link_to I18n.t('buttons.edit'), edit_order_path(order), class: 'btn btn-primary'
        - if user_superadmin?
          th
            = link_to I18n.t('buttons.delete'), order_path(order), method: :delete, class: 'btn btn-danger'

  = will_paginate previous_label: I18n.t('buttons.previous_label'), next_label: I18n.t('buttons.next_label')

app/views/orders/new.html.slim
.form_container
  = simple_form_for @order do |f|
    = f.input :title
    = f.input :customer_info
    = f.input :order_info
    = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
    = f.input :status, as: :hidden, input_html: { value: 'active' }
    / = f.simple_fields_for :packages do |package|
    /   = render partial: 'orders/package_fields', f: package
    / = link_to_add_association 'Add package', f, :packages, id: 'add-package-btn'
    / = f.simple_fields_for :packages do |package|
    /   = render partial: 'orders/packages_fields', f: package
    / = link_to_add_fields 'Add package', f, :packages

    = f.button :submit, I18n.t('orders.create'), class: 'btn btn-primary submit-button'

app/views/orders/show.html.slim
.form_container
  .form-group
    .field-label.control-label
      = I18n.t('orders.id')
    .field.form-control
      = @order.id
  .form-group
    .field-label.control-label
      = I18n.t('orders.title')
    .field.form-control
      = @order.title
  .form-group
    .field-label
      = I18n.t('orders.customer_info')
    .field.form-control
      = @order.customer_info
  .form-group
    .field-label
      = I18n.t('orders.order_info')
    .field.form-control
      = @order.order_info
  .form-group
    .field-label
      = I18n.t('orders.status')
    .field.form-control
      = order_statuses_ru[@order.status.to_sym]
  .form-group
    .field-label
      = I18n.t('orders.user')
    .field.form-control
      = @order.user.email
  - if @order.packages.present?
    .form-group
      .field-label
        = I18n.t('packages.main_title')
      .field
        - @order.packages.each do |package|
          .package-block
            = link_to "Идентификатор: #{package.id}, Размер #{package.size} ", package_path(package), class: 'btn btn-info'
  .form-group
    .field
      = link_to I18n.t('orders.update'), edit_order_path(@order), class: 'btn btn-primary'